modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/dhyces/just-a-wrench/issues" #optional
[[mods]] #mandatory
modId="waxablecoral" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Waxable Coral" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/just-a-wrench"
logoFile="icon.png"
authors="Dhyces" #optional
description='''
Wax your coral! Stays alive even when it's dry!
'''

[[dependencies.waxablecoral]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[43,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.waxablecoral]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
